# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Iandh - Project Blog
tagline:             'Personal Ramblings'
description:         'Project updates about brewing & embedded systems.'
url:                 http://elasticmodulus.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              iandh
  url:               http://elasticmodulus.com
  email:             ian@elasticmodulus.com

# Custom vars
# version:             1.0.0
